#
# Generated by the Apple Project Builder.
#
# NOTE: Do NOT change this file -- Project Builder maintains it.
#
# Put all of your customizations in files called Makefile.preamble
# and Makefile.postamble (both optional), and Makefile will include them.
#

NAME = MPWFoundation

PROJECTVERSION = 2.8
PROJECT_TYPE = Framework

GLOBAL_RESOURCES = Concepts.rtf Log.rtf Notes.rtf Readme.rtf

CLASSES = MPWObject.m NSNil.m NSInvocationAdditions.m\
          NSStringAdditions.m CodingAdditions.m MPWObjectCache.m\
          NSRectAdditions.m MPWScanner.m NSDictAdditions.m\
          MPWRuntimeAdditions.m NSObjectAdditions.m MPWPoint.m\
          MPWRect.m NSDataPrivateMemoryMapping.m MPWTrampoline.m\
          MPWMsgExpression.m MPWAssociation.m MPWIgnoreTrampoline.m

HFILES = AccessorMacros.h DebugMacros.h MPWObject.h NSNil.h\
         MPWFoundation.h NSInvocationAdditions.h NSStringAdditions.h\
         NSInvocationAdditions_lookup.h CodingAdditions.h\
         MPWObjectCache.h NSRectAdditions.h MPWScanner.h\
         NSDictAdditions.h MPWRuntimeAdditions.h NSObjectAdditions.h\
         MPWPoint.h MPWRect.h MPWTrampoline.h MPWMsgExpression.h\
         MPWAssociation.h MPWIgnoreTrampoline.h bytecoding.h

CFILES = bytecoding.c

SUBPROJECTS = Comm.subproj Collections.subproj Streams.subproj\
              Threading.subproj

OTHERSRCS = Makefile.preamble Makefile Makefile.postamble m.template\
            h.template


MAKEFILEDIR = $(MAKEFILEPATH)/pb_makefiles
CURRENTLY_ACTIVE_VERSION = YES
DEPLOY_WITH_VERSION_NAME = A
CODE_GEN_STYLE = DYNAMIC
MAKEFILE = framework.make
NEXTSTEP_INSTALLDIR = /Local/Library/Frameworks
WINDOWS_INSTALLDIR = $(NEXT_ROOT)/Local/Library/Frameworks
PDO_UNIX_INSTALLDIR = /Local/Library/Frameworks
LIBS = 
DEBUG_LIBS = $(LIBS)
PROF_LIBS = $(LIBS)


FRAMEWORK_PATHS = -F$(NEXT_ROOT)/Local/Library/Frameworks
NEXTSTEP_PB_CFLAGS = -O4
FRAMEWORKS = -framework Foundation -framework System
PUBLIC_HEADERS = AccessorMacros.h DebugMacros.h MPWFoundation.h\
                 MPWObject.h NSInvocationAdditions.h\
                 NSInvocationAdditions_lookup.h CodingAdditions.h\
                 MPWObjectCache.h NSRectAdditions.h MPWScanner.h\
                 NSStringAdditions.h NSObjectAdditions.h MPWRect.h\
                 MPWPoint.h MPWTrampoline.h MPWMsgExpression.h\
                 MPWAssociation.h MPWIgnoreTrampoline.h bytecoding.h\
                 MPWRuntimeAdditions.h

PROJECT_HEADERS = AccessorMacros.h DebugMacros.h MPWFoundation.h\
                  MPWObject.h NSInvocationAdditions.h\
                  NSInvocationAdditions_lookup.h CodingAdditions.h\
                  MPWObjectCache.h NSRectAdditions.h MPWScanner.h\
                  MPWRuntimeAdditions.h NSStringAdditions.h\
                  NSObjectAdditions.h MPWRect.h MPWPoint.h\
                  MPWTrampoline.h MPWMsgExpression.h MPWAssociation.h\
                  MPWIgnoreTrampoline.h bytecoding.h

PRECOMPILED_HEADERS = MPWFoundation.h



NEXTSTEP_OBJCPLUS_COMPILER = /usr/bin/cc
WINDOWS_OBJCPLUS_COMPILER = $(DEVDIR)/gcc
PDO_UNIX_OBJCPLUS_COMPILER = $(NEXTDEV_BIN)/gcc
NEXTSTEP_JAVA_COMPILER = /usr/bin/javac
WINDOWS_JAVA_COMPILER = $(JDKBINDIR)/javac.exe
PDO_UNIX_JAVA_COMPILER = $(JDKBINDIR)/javac

include $(MAKEFILEDIR)/platform.make

-include Makefile.preamble

include $(MAKEFILEDIR)/$(MAKEFILE)

-include Makefile.postamble

-include Makefile.dependencies
