#!/bin/bash
#
#


cd /home/gnustep

echo Downloading libobjc2
curl -O ftp://ftp.gnustep.org/pub/gnustep/libs/libobjc2-1.8.1.tar.gz
#git checkout --recursive https://github.com/gnustep/libobjc2

echo Downloading GNUstep Make
curl -O ftp://ftp.gnustep.org/pub/gnustep/core/gnustep-make-2.7.0.tar.gz

echo Downloading GNUstep Base via git
curl -O ftp://ftp.gnustep.org/pub/gnustep/core/gnustep-base-1.26.0.tar.gz
# git clone https://github.com/gnustep/libs-base.git
