#!/bin/bash
cd ~gnustep/Build/obj
cp  *.so* /usr/GNUstep/Local/Library/Libraries/
cd /usr/local/lib/
cp  libBlocksRuntime.so libdispatch.so /usr/GNUstep/Local/Library/Libraries/
cd /usr/
tar zcf ~/ObjS-GNUstep-installed.tgz GNUstep
cp /usr/lib/aarch64-linux-gnu/libmicrohttpd.* /usr/GNUstep/Local/Library/Libraries/ 
