#!/bin/bash
#
# Written by Tobias Lensing, http://tlensing.org
# For more information see http://blog.tlensing.org/2013/02/24/objective-c-on-linux-setting-up-gnustep-clang-llvm-objective-c-2-0-blocks-runtime-gcd-on-ubuntu-12-04/
#

PKG_OK=$(dpkg-query -W --showformat='${Status}\n' curl | grep "install ok installed")
echo Checking for curl: $PKG_OK
if [ "" == "$PKG_OK" ]; then
  apt-get install curl -y
fi

echo Downloading libobjc2
curl -O ftp://ftp.gnustep.org/pub/gnustep/libs/libobjc2-1.8.1.tar.gz

echo Downloading GNUstep Make
curl -O ftp://ftp.gnustep.org/pub/gnustep/core/gnustep-make-2.7.0.tar.gz

echo Downloading GNUstep Base
curl -O ftp://ftp.gnustep.org/pub/gnustep/core/gnustep-base-1.25.1.tar.gz

PKG_OK=$(dpkg-query -W --showformat='${Status}\n' libdispatch-dev | grep "install ok installed")
echo Checking for libdispatch-dev: $PKG_OK
if [ "" != "$PKG_OK" ]; then
	apt-get remove libdispatch-dev -y
fi

set -e

echo Installing required packages
apt-get install build-essential clang libblocksruntime-dev libkqueue-dev libpthread-workqueue-dev gobjc libxml2-dev cmake  -y

echo Unpacking archives
tar xvfz libobjc2-1.8.1.tar.gz
tar xvfz gnustep-make-2.7.0.tar.gz
tar xvfz gnustep-base-1.25.1.tar.gz

echo Installing libobjc2
export CC=clang

cd gnustep-make-2.7.0
./configure
make install
cd ..

cd libobjc2-1.8.1
mkdir Build
cd Build
cmake ..
make install
cd ../..


cd gnustep-make-2.7.0
make clean
./configure --with-library-combo=ng-gnu-gnu
make install
cd ..


cd gnustep-base-1.25.1
#./configure
make install
cd ..

apt-get install libdispatch-dev

echo Installation script finished successfully
