#!/bin/bash
#
#


cd /home/gnustep

echo Downloading libobjc2
git clone --recursive https://github.com/gnustep/libobjc2

echo Downloading GNUstep Make
curl -O ftp://ftp.gnustep.org/pub/gnustep/core/gnustep-make-2.7.0.tar.gz

echo Downloading GNUstep Base via git
git clone https://github.com/gnustep/libs-base.git
